### ISSUE TITLE
How to store the state in a struct

### ISSUE THREAD

**Issue by jeanmanguy** [rusty-rockets/sm#5]
Sorry, surely a beginner question, I couldn't find in the doc or in the examples how I should store the state in a struct so multiple instances could be at different states, for example. What is the type of the generated states by the macro? I don't think I should store the `sm` object, no?

**Comment by JeanMertz** [comment]
Hey @jeanmanguy,

The `sm!` macro returns the [`Machine` trait object](https://docs.rs/sm/latest/sm/trait.Machine.html).

However, in order to validate the state machine at compile time, you get a new trait object back with different associated types each time the machine transitions to a different state.

I haven't used the library in a while, and my Rust is a bit _rusty_ as I've been focused on Go for my day job lately, but I'd say you'd either have to store it as a `dyn` type in a `Box`, or you have to use generics to store the machine.

Let me know if that works for you.

**Comment by jeanmanguy** [comment]
I will try that that, thanks

**Comment by WinstonHartnett** [comment]
> I haven't used the library in a while, and my Rust is a bit _rusty_ as I've been focused on Go for my day job lately, but I'd say you'd either have to store it as a `dyn` type in a `Box`, or you have to use generics to store the machine.

Didn't want to necrobump, but `Machine` isn't trait object-safe because it uses `Self` (a stand-in for a concrete type) as a return type. Since each transition changes the Machine's type (which is the intention for it to be type-safe), I'm not sure how generics would work. Are there any other alternatives to store the machine? @jeanmanguy did you find anything that worked?

**Comment by ArekPiekarz** [comment]
You can use Rust's `enum` to store every state in one field and then `match` on it to get different behaviors.

**Comment by WinstonHartnett** [comment]
That works. Thanks!

**Comment by tmilker** [comment]
@ArekPiekarz @WinstonHartnett Can you provide a quick example of how to do this?

**Comment by ArekPiekarz** [comment]
@tmilker I expanded the example from README to show how the type of the machine changes with each transition and how to store it in a field of another struct (Engine) using enum (generated Lock::Variant):
```rust
use sm::sm;

sm! {
    Lock {
        InitialStates { Locked }

        TurnKey {
            Locked => Unlocked
            Unlocked => Locked
        }

        Break {
            Locked, Unlocked => Broken
        }
    }
}

struct Engine
{
    machine: Lock::Variant
}

use Lock::*;
use Lock::Variant::*;

impl Engine
{
    fn handle(mut self, event: Break)
    {
        self.machine = match self.machine {
            InitialLocked(lock) => BrokenByBreak(lock.transition(event)),
            UnlockedByTurnKey(lock) => BrokenByBreak(lock.transition(event)),
            LockedByTurnKey(lock) => BrokenByBreak(lock.transition(event)),
            BrokenByBreak(lock) => BrokenByBreak(lock)
        }
    }
}

fn main() {
    // types on the left written explicitly for educational purpose
    let lock: Machine<Locked,sm::NoneEvent> = Machine::new(Locked);
    let lock: Machine<Unlocked,TurnKey> = lock.transition(TurnKey);

    let engine = Engine{machine: UnlockedByTurnKey(lock)};
    engine.handle(Break);
}
```

**Comment by tmilker** [comment]
@ArekPiekarz Now that I've had some time to look at your example: There's no way to just store the machine and transition that?

I haven't found any state machine patterns or crates for Rust that don't feel like a hack or toy in some way.
